name: photo_app
description: Intern Project

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  dio: ^5.2.1+1
  elementary: ^2.0.0

  flutter:
    sdk: flutter

  flutter_blurhash: ^0.7.0
  get_it: ^7.6.0
  injectable: ^2.1.2
  injectable_generator: ^2.1.6

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter

  surf_lint_rules: ^2.1.0

flutter:
  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope-Regular.ttf

  uses-material-design: true