name: photo_app
description: Intern Project

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  dio: ^5.2.1+1
  elementary: ^2.0.0

  flutter:
    sdk: flutter

  flutter_blurhash: ^0.7.0
  get_it: ^7.6.0
  injectable: ^2.1.2
  injectable_generator: ^2.1.6
  json_annotation: ^4.8.1
  retrofit: '>=4.0.0 <5.0.0'

dev_dependencies:
  build_runner: ^2.4.5

  flutter_test:
     sdk: flutter

  json_serializable: ^6.7.0

  retrofit_generator: '>=5.0.0 <6.0.0'

  surf_lint_rules: ^2.1.0

flutter:
  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope-Regular.ttf

  uses-material-design: true